### PR TITLE
HTML-JAVASCRIPT-CSS by Ivan Genchev -Client Information Form.

### PR DESCRIPTION
**Pull request by freekman**
1)Task three

Make an HTML page containing a form for data entry user (first name, last name, EGN, age, address, password, confirm password).

taskthreeform

### CODE REVIEW

**Comment by mgenov** [comment]
Please add screenshot of the form in the description of the pull request. There are plenty of plugins for chrome for making partial screenshots.

**Comment by freekman** [comment]
Screen shot for the form has been added

**Comment by mgenov** [comment]
No, it's not in the body of the pull request.

**Comment by mgenov** [comment]
Note that you can paste the task description in the body of the pull request, it will give me more information then "Task 3", cause I don't know what Task 3 is on this theme, and I have to go to documentation to read it.

**Pull request closed without merging**
